/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shapesort;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

public class ShapeTest {
    @Test
    @Disabled("Not implemented yet")
    void testShapeComparator() {
    }

    @Test
    @Disabled("Not implemented yet")
    void testShapeSort() {
    }
}
